### ISSUE TITLE
The chart crashes almost always if someone clicks and scrolls

### ISSUE THREAD

**Issue by MrCsabaToth** [TrackMyIndoorWorkout/TrackMyIndoorWorkout#220]
Unfortunately the call stack does not have a level where I could catch it. Maybe it's the interference of the listview up-down scroll vs the chart's up-down pan? It comes when long pressing for a chart trackball and then immediately swipe up-down over the chart.

Opened Syncfusion issue: https://github.com/syncfusion/flutter-widgets/issues/463

```
======== Exception caught by gesture ===============================================================
The following _CastError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      getNearestChartPoints (package:syncfusion_flutter_charts/src/chart/common/common.dart:1644:59)
#1      TrackballRenderingDetails.generateAllPoints (package:syncfusion_flutter_charts/src/chart/user_interaction/trackball.dart:897:13)
#2      TrackballBehavior.show (package:syncfusion_flutter_charts/src/chart/user_interaction/trackball.dart:436:36)
#3      TrackballBehaviorRenderer.onTouchMove (package:syncfusion_flutter_charts/src/chart/user_interaction/trackball.dart:572:52)
#4      ContainerArea._performLongPressMoveUpdate (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:3206:18)
#5      ContainerArea.build.<anonymous closure>.<anonymous closure> (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:2307:25)
#6      LongPressGestureRecognizer._checkLongPressMoveUpdate.<anonymous closure> (package:flutter/src/gestures/long_press.dart:756:85)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
#8      LongPressGestureRecognizer._checkLongPressMoveUpdate (package:flutter/src/gestures/long_press.dart:756:11)
#9      LongPressGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/long_press.dart:652:9)
#10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:558:9)
#11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:440:19)
#17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#18     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
#19     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#20     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#26     _invoke1 (dart:ui/hooks.dart:185:10)
#27     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#28     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
(elided 3 frames from dart:async)
Handler: "onLongPressMoveUpdate"
Recognizer: LongPressGestureRecognizer#26cf0
  debugOwner: GestureDetector
  state: possible
```

**Comment by MrCsabaToth** [comment]
Supposedly [19.4.55](https://pub.dev/packages/syncfusion_flutter_charts/versions/19.4.55) would fix this but I still see the `seriesRendererDetails.visibleDataPoints!.isNotEmpty == true` clause in the `show` function of the `trackball.dart`.

**Comment by MrCsabaToth** [comment]
20.1.56 still has this crash. When will ti be fixed?

**Comment by MrCsabaToth** [comment]
Still crashes

**Comment by MrCsabaToth** [comment]
With the latest code I don't experience the crash any more.
