### ISSUE TITLE
Navgating from the Find Devices screen to the Recording Screen crashes

### ISSUE THREAD

**Issue by MrCsabaToth** [TrackMyIndoorWorkout/TrackMyIndoorWorkout#425]
Looks like that it is caused (at least partially) by repeated `getConnectedDevices` calls while navigating away:
```
Cmd line: dev.csaba.track_my_indoor_exercise;"main" prio=5 tid=2 RUNNABLE sysTid=30653;
  at android.os.BinderProxy.transactNative(Native Method);
  at android.os.BinderProxy.transact(BinderProxy.java:635);
  at android.bluetooth.IBluetoothGatt$Stub$Proxy.getDevicesMatchingConnectionStates(IBluetoothGatt.java:1736);
  at android.bluetooth.BluetoothManager.getDevicesMatchingConnectionStates(BluetoothManager.java:200);
  at android.bluetooth.BluetoothManager.getConnectedDevices(BluetoothManager.java:160);
  at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin.lambda$onMethodCall$3$com-boskokg-flutter_blue_plus-FlutterBluePlusPlugin(FlutterBluePlusPlugin.java:333);
  at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin$$ExternalSyntheticLambda2.op(Unknown Source:6);
  at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin.ensurePermissionBeforeAction(FlutterBluePlusPlugin.java:756);
  at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin.onMethodCall(FlutterBluePlusPlugin.java:317);
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258);
  at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295);
  at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322);
  at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12);
  at android.os.Handler.handleCallback(Handler.java:938);
  at android.os.Handler.dispatchMessage(Handler.java:99);
  at android.os.Looper.loopOnce(Looper.java:233);
  at android.os.Looper.loop(Looper.java:344);
  at android.app.ActivityThread.main(ActivityThread.java:8212);
  at java.lang.reflect.Method.invoke(Native Method);
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584);
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034);
```

I already removed the connection indicator due to this problem almost two years ago:
https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/commit/8358b5b0

This time I'd want to pause the stream once the navigation logic starts to prepare for navigating away (and connecting to device which possibly induce the stream poll).

**Comment by MrCsabaToth** [comment]
I've made serious changes to minimize the amount of calls to the Bluetooth stack. This involves:
* throttling the scan call stream
* wrapping the scan call stream so there can be a subscription which can be paused when navigating away starts (while trying to examine the destination device the app may connect to it - for example to decide if a CSC sensor is speed or cadence sensor -  so to avoid rebuilds pause hopefully helps)
* Eliminating StreamBuilders based on the boolean `FlutterBluePlus.instance.isScanning` by utilizing the private variable `_isScanning` what we have anyway
* Eliminating StreamBuilders based on the boolean `BluetoothDeviceState`: we'd only call the async `await ...device?.state.first == BluetoothDeviceState.connected` inside the click handler. This way the icons (fitness machine or HRM) won't indicate disconnection though, however we make this trade-off to cut down possible calls to the Bluetooth stack.

**Comment by MrCsabaToth** [comment]
After the major refactoring the Bluetooth Stack still ANRd, but this time during simple scanning (not when navigating away). The scan resulted in no hits, and the Bluetooth stack call triggered the ANR logic of Android again:
```
Cmd line: dev.csaba.track_my_indoor_exercise;"main" prio=5 tid=2 TIMED_WAITING sysTid=32152;
  at java.lang.Object.wait(Native Method);
  at java.lang.Object.wait(Object.java:442);
  at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.startRegistration(BluetoothLeScanner.java:439);
  at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:290);
  at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:155);
  at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin.startScan21(FlutterBluePlusPlugin.java:923);
  at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin.startScan(FlutterBluePlusPlugin.java:852);
  at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin.lambda$onMethodCall$0$com-boskokg-flutter_blue_plus-FlutterBluePlusPlugin(FlutterBluePlusPlugin.java:264);
  at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin$$ExternalSyntheticLambda4.op(Unknown Source:6);
  at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin.ensurePermissionBeforeAction(FlutterBluePlusPlugin.java:756);
  at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin.lambda$onMethodCall$1$com-boskokg-flutter_blue_plus-FlutterBluePlusPlugin(FlutterBluePlusPlugin.java:262);
  at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin$$ExternalSyntheticLambda0.op(Unknown Source:6);
  at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin.ensurePermissionBeforeAction(FlutterBluePlusPlugin.java:756);
  at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin.onMethodCall(FlutterBluePlusPlugin.java:260);
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258);
  at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295);
  at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322);
  at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12);
  at android.os.Handler.handleCallback(Handler.java:938);
  at android.os.Handler.dispatchMessage(Handler.java:99);
  at android.os.Looper.loopOnce(Looper.java:233);
  at android.os.Looper.loop(Looper.java:344);
  at android.app.ActivityThread.main(ActivityThread.java:8212);
  at java.lang.reflect.Method.invoke(Native Method);
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584);
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034);
E/ANR_LOG ( 6127): >>> msg's executing time is too long
E/ANR_LOG ( 6127): Blocked msg = { when=-2s7ms what=0 target=android.os.Handler callback=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 } , cost  = 2007 ms
E/ANR_LOG ( 6127): >>>Current msg List is:
E/ANR_LOG ( 6127): Current msg <1> = { when=0 what=0 target=android.os.Handler callback=android.bluetooth.le.BluetoothLeScanner$1 }
E/ANR_LOG ( 6127): >>>CURRENT MSG DUMP OVER<<<
I/Quality ( 6127): Blocked msg = Package name: dev.csaba.track_my_indoor_exercise [ schedGroup: 5 schedPolicy: 0 ] process the message: { when=-2s7ms what=0 target=android.os.Handler callback=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 } took 2007 ms
```

**Comment by MrCsabaToth** [comment]
After 1.5 days of painful struggling a phone restart normalized the situation. Possibly the many debug sessions got the Bluetooth stack screwed up. I'll still keep the changes because long term they can be beneficial.
