### ISSUE TITLE
KayakFirst doesn't record workout

### ISSUE THREAD

**Issue by MrCsabaToth** [TrackMyIndoorWorkout/TrackMyIndoorWorkout#430]
We'll need to introduce more delays so the console can catch up with the commands.

**Comment by MrCsabaToth** [comment]
Ref #426
Ref #397

**Comment by MrCsabaToth** [comment]
In the logs it seems that the polling is not effective / not going on because I don't see any responses to the data polling [1204202313.txt](https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/files/11215881/1204202313.txt)

**Comment by MrCsabaToth** [comment]
Repro video: https://youtu.be/HqeCaciDg38
I now tested a release version on a test phone, and confirmed that the Instant Measurement Start can be still a problem (without the extra delays introduced as a fix). But I was able to record a workout manually. But there's still definitely somthing off.

**Comment by MrCsabaToth** [comment]
It seems that the beta release version on my Moto test phone connected well now (after console power on, app fresh start and Instant Measurement Start). Hopefully Akos's test will pass as well with all the delay and feedback based enhancements.

**Comment by MrCsabaToth** [comment]
It got even worse for Akos. From the logs it looks like the reset ("1") command goes out and the response arrive, but then no trace of the handshake ("2") command going out. So it gets stuck somehow, although the logic to wait for the responses have timeouts for safety. So I'm clueless.
* Log of the APK build: [1304202309.txt](https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/files/11227191/1304202309.txt)
* Log of the beta installed app: [1304202316.txt](https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/files/11227192/1304202316.txt)
* Accompanying video: https://youtu.be/MCPSmlUnXrc

I tested the beta release 144 with Beth's Pixel 6 and it worked. It also works on the Moto test phone: https://youtu.be/QoytLGxZ9Rk
Nevertheless I refactored the code a little. Hopefully it helps.

**Comment by MrCsabaToth** [comment]
The refactored wait / delay logic is released to the beta channel as build 145

**Comment by MrCsabaToth** [comment]
Akos tested my latest build and it didn't bring improvement to them (
[1504202310.txt](https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/files/11241193/1504202310.txt)
). According to him the downturn started with the build 142. The question is what happened? I transitioned from the New Handshake (athlete and boat weight setting along with the setting) to the more traditional regular Handshake which sets the athlete weight and the sport. Both commands also set the epoch time along with the time zone offset. Another change was to remove parameter command and introduce the display configuration, but the first version of that worked. So the question is what code changes happened since the build 141, and what could be the difference between my environments and KayakFirsts's test environments. Also we know from the logs that the reset command goes out and the repsonse comes back, but the handshake command doesn't seem to go out. The app doesn't crash though, it remains responsive.

1. Time zone. This is definitely a difference. Especially since FIBO expo it's in Germany. Although Germany is CET (UTC+1) time zone just like Hungary. The code which depends on the time zone is the epoch time + TZ offset of the handshake command. The `now.timeZoneOffset.inMinutes` call is not `async` and I don't see a major reason why it would fail or get stuck.
2. The other thing is a faint suspicion: all the command paths got sprinkled with `FlutterBluePlus.instance.isOn` calls. The idea behind this was that with KayakFirst I significantly changed the way I treat devices regarding how eager I would be to disconnect from them and how soon I'd start interacting with them. In the past I was eager to disconnect them to avoid keeping devices "bogged down" with a BT connection. Along the same principle I only started data collection after the measurement start. The new paradigm is that I try to keep the connection alive and also eager to start the data acquisition soon after connection, even if the measurement haven't started. This is so I could also observe KayakFirst's responses to non poll commands. Because of this paradigm change however I wanted the code to be more robust against someone turning the console off, or turning the phone BT off. I already experienced a weird ANR sort of bug related to changes about this: https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/commit/898f7a53e3cb2b42aa9343cbaea45368e81c76f4

Essentially the `fitnessEquipment.device?.state.first` async call waited forever. It didn't crash the app, and didn't result in a crass which would surface to the Flutter level, however in the LogCat (lower level logs) I saw there was a crash in the Android Bluetooth protocol stack. Therefore I added an async `timeout` call (which was elaborated by the https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/commit/3d253d3321403ef57c8c6ce8cd5fa21afb420557 later) to make sure there wouldn't be an infinite wait there. Since then I also utilized `timeout` calls along the async delay calls related to KayakFirst post connect logic. The bottom line is sometimes for whatever reason the underlying Android Bluetooth protocol stack can be fickle and just poop itself. So the less I poke it the better.

Another phenomena was in the ancient versions the Find Devices screen still had a generic Bluetooth connection icon, that induced a periodic call into the Bluetooth protocol stack. That also sometimes (especially after long runtime, or other commands into the protocol stack) caused the BT plugin and protocol stack to shit itself. This is the reason why I unfortunately ended up removing not just the BT on/off status boolean stream UI feedback, but also the per device connected status boolean streams. I had to dumb down the app to make it more stable and robust.

My faint suspicion is that my cautiousness of sprinkling `FlutterBluePlus.instance.isOn` calls may make the mimosa-like BT protocol stack upset. So in case of the KayakFirst crew's devices that call might cause a crash and goes into an endless wait? We know that the Recording screen already checks this boolean right after the navigation happens, so there's no need to check it again and again just after few seconds of wait. So I removed a lot of these calls. With the latest commits and produced a custom apk for Akos. We'll see how it fares. The other thing is though: even if that call waits forever why a higher level async await timeout wouldn't snap the call out of that?

**Comment by MrCsabaToth** [comment]
The mentioned `FlutterBluePlus.instance.isOn` removal / reorganization / refactor commits:
* https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/commit/a671b3542f3bfe5e826a37ad008879e6a5eb9002
* https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/commit/d8b2b2e800781b324b48f2fd13fb4a4fc9aba49b

**Comment by MrCsabaToth** [comment]
It sounds like there's still no break through according to Akos's test. I have to heavily debugPrint line-by-line to identify which code line is the culprit.

**Comment by MrCsabaToth** [comment]
So the latest log before I gave Akos an line-by-line logger version:
[1604202308.txt](https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/files/11246327/1604202308.txt)

**Comment by MrCsabaToth** [comment]
I made another change, a pacman exception handler:
* https://medium.com/lost-but-coding/stop-using-widgetsflutterbinding-ensureinitialized-ddff6978ad55
* https://github.com/flutter/flutter/issues/72351
* https://medium.com/geekculture/mastering-flutter-zones-ea28fe6a6ca6
* https://dartpad.dev/workshops.html?webserver=https://handling-errors-gracefully.web.app
* https://firebase.flutter.dev/docs/crashlytics/usage/

**Comment by MrCsabaToth** [comment]
The pacman exception handling (by `runZonedGuarded`'s error handler) helped and it's visible by the latest log of Akos that essentially the handshake's characteristic.write crashes. One interesting thing that it's not a `PlatformException` as the code expects. Now back to the drawing board to plan what to do about this.
[1704202307.txt](https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/files/11251699/1704202307.txt)

**Comment by MrCsabaToth** [comment]
I've faced similar thing before during spin-down and that has a code which tries to repeat a command one more time. The `connectAndDiscover` already has a "retry" feature. However probably I should replace every `PlatformException` catch with a generic `Exception` based on this log, but the analyzer's gonna be trippin' about that. What a mess!

**Comment by MrCsabaToth** [comment]
I replaced the exceptions, refactored some retry logics and increased delays. Akos reports that now he can measure, however it's still unstable right after the start (the first measurement).

1. First log: [1804202319.txt](https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/files/11268035/1804202319.txt) "Bekapcs és csatlakozás után a kijelzőn láttam hogy felvillan a töltöttség jelzés ami azt jelenti hogy átment normál fw-be. De utána egyből visszaugrott.
Utána az app azt mondta fut de nem nem ibdult el az ergo. Képernyőn elindítottam de adat nem jelent meg. Viszont stop-ot megkapta mikor kiléptem. Visszaléptem megint csatlakozás és indult az evezés, lett adat, minden."
2. Second log: [1804202320.txt](https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/files/11268038/1804202320.txt) "Első bekapcs semmi, nem ugrott át normálba. Stopot vette, majd pár ki és bekapcs és párszor normálba ugrottmeg vissza, majd egyszer elsőre indult az evezés is.
A stopot mindig vette, és úgy indítottam hogy stop után újra akkor el is indult. Ilyenkor persze nem azok az adatok jelentek meg a képernyön ami kell, hanem az idő mindenhol hiszem nem volt előtte képernyő parancs. Ha lecsatlakoztam majd vissza úgy hogy az ergó bekapcsolva maradt akkor másodikra simán indult és a képernyő kiosztás is jó volt."

**Comment by MrCsabaToth** [comment]
This might be also plugin related: https://github.com/boskokg/flutter_blue_plus/issues/242
Seems like others had similar issues: https://github.com/boskokg/flutter_blue_plus/issues/68

**Comment by MrCsabaToth** [comment]
The current sequence of events when clicking on the KayakFirst for a workout:

1. BT connect to the console
2. Query the services and characteristics (=discovery).
3. Verify that the KayakFirst 0x0FF1 service and the data characteristic is present, also verify that the manufacturer name is "Manufacturer Name".
4. Attach to the data characteristic and perform a `setNotifyValue(true)` to listen on the replies (asynchronously) to the command I'll send later.
5. At that point the machine haven't received any command yet. Wait half a second.
6. Send the reset command ("1") (this crashes in the logs).
7. Wait for 3 seconds at max, if I capture the response earlier than I continue earlier. (In the logs the response eventually arrives but as a first response to the handshake "2" command).
8. Wait for 2 seconds (fixed, on top of the previous wait for the response, so I would not blast the console with another right away after I capture a response to a previous command).
9. Send the handshake (2) command (including parameters). (This crashes as well in the logs).
10. Wait for 3 seconds at max, if I capture the response earlier than I continue earlier.
11. Wait for half a second (fixed).
12. Send the screen configuration command.
13. Wait for 3 seconds at max, if I capture the response earlier than I continue earlier.
14. Wait for 2 seconds fixed (before I'd turn towards the workout start commands - only in case the Instant Measurement Start is on. I noticed that this latter can make things worse).

All data poll commands crash as well until eternity.

**Comment by MrCsabaToth** [comment]
Akos's request regarding the steps above:
1. Step 7: I'd need to keep sending the reset command until I receive a legit response (such as "1;1;15305302073")
2. Step 14: needs more than 3 seconds of wait. The screen configuration command (Step 12) the console will respond immediately, but the actual execution could take 4-5 seconds. So the wait time should be 5 seconds at Step 14 (or we may tune it even further).
3. Any other command only requires 1 second wait at max, but usually even 100-200ms

**Comment by MrCsabaToth** [comment]
Crash stack from the app's logs:
```
{DATA_HANDLER}  {_waitForResponse}  {false}  {18 April 2023 07:37:03.486 PM}  {INFO}
{DATA_HANDLER}  {_executeControlOperationCore command}  {5;0;2;5;11;15
}  {18 April 2023 07:37:03.991 PM}  {INFO}
{DATA_HANDLER}  {_executeControlOperationCore}  {controlPoint.write; Exception: Failed to write the characteristic; #0      BluetoothCharacteristic.write.<anonymous closure> (package:flutter_blue_plus/src/bluetooth_characteristic.dart:135)
#1      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#2      KayakFirstDescriptor._executeControlOperationCore (package:track_my_indoor_exercise/devices/device_descriptors/kayak_first_descriptor.dart:133)
<asynchronous suspension>
#3      KayakFirstDescriptor.configureDisplay (package:track_my_indoor_exercise/devices/device_descriptors/kayak_first_descriptor.dart:213)
<asynchronous suspension>
#4      KayakFirstDescriptor.postPumpStart (package:track_my_indoor_exercise/devices/device_descriptors/kayak_first_descriptor.dart:237)
<asynchronous suspension>
#5      FitnessEquipment.postPumpStart (package:track_my_indoor_exercise/devices/gadgets/fitness_equipment.dart:521)
<asynchronous suspension>
#6      RecordingState._connectOnDemand (package:track_my_indoor_exercise/ui/recording.dart:278)
<asynchronous suspension>
}  {18 April 2023 07:37:04.023 PM}  {ERROR}
{FITNESS_EQUIPMENT}  {_listenToData loop}  {measuring false calibrating false [50, 59, 50, 51, 48, 51, 48, 48, 49, 66, 59, 50, 50, 49, 48, 50, 54, 59, 50, 48]}  {18 April 2023 07:37:04.081 PM}  {INFO}
{FITNESS_EQUIPMENT}  {_listenToData loop}  {Kayak First: 2;2303001B;221026;20}  {18 April 2023 07:37:04.082 PM}  {INFO}
{FITNESS_EQUIPMENT}  {_listenToData loop}  {measuring false calibrating false [49, 48, 48, 56, 59, 66, 76, 53, 48, 49, 53, 13, 10]}  {18 April 2023 07:37:04.127 PM}  {INFO}
{FITNESS_EQUIPMENT}  {_listenToData loop}  {Kayak First: 1008;BL5015
}  {18 April 2023 07:37:04.128 PM}  {INFO}
```
I don't know the native parts of the crash because that's in the LogCat and I cannot reproduce ti locally so far.

**Comment by MrCsabaToth** [comment]
Akos had some results, we still need to iterate.

**Comment by MrCsabaToth** [comment]
The latest MTU size error with 17 bytes (which was a result of https://github.com/boskokg/flutter_blue_plus/commit/625ccd1a687395ca215dd7306f9f4a54ea523ee4 and resulted in https://github.com/boskokg/flutter_blue_plus/issues/412) shined a light on the fact that I was not chunking the commands. I'd need to introduce the chunking by 20 byte MTU size.

**Comment by MrCsabaToth** [comment]
I recorded a video on how the app works with my console even with "instant measurement start" on: https://youtu.be/7YHuVoxV3_c

**Comment by MrCsabaToth** [comment]
Watch out for https://github.com/boskokg/flutter_blue_plus/issues/412 about MTU!

**Comment by MrCsabaToth** [comment]
Latest test of Akos shows an endless flood of `FlutterBluePlusException: writeCharacteristic: (code: 10) UNKNOWN_GATT_ERROR (10)`. Not sure yet what is this code 10. I'll first try to produce a new build because there were 20+ more version bumps for Flutter Blue Plus since the test build.

[DebugLogs20231011T115535529298Z.txt.zip](https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/files/12874370/DebugLogs20231011T115535529298Z.txt.zip)

**Comment by MrCsabaToth** [comment]
In a recent debug session with the debug console before my travel I ran into a glitch. The console didn't reply with a dataset containing 23 elements, but only 11:

Full packet:
```
[54, 59, 49, 55, 48, 50, 51, 52, 55, 54, 57, 56, 50, 50, 54, 59, 48, 59, 48, 59]
6;1702347698226;0;0;
[48, 59, 48, 46, 48, 48, 59, 48, 59, 49, 59, 48, 59, 53, 53, 59, 53, 46, 49, 49]
0;0.00;0;1;0;55;5.11
[59, 53, 46, 48, 52, 59, 57, 48, 59, 56, 50, 59, 51, 57, 59, 51, 57, 59, 57, 55]
;5.04;90;82;39;39;97
[59, 57, 55, 59, 49, 57, 53, 59, 49, 57, 53, 59, 50, 53, 55, 59, 50, 53, 53, 59]
;97;195;195;257;255;
[49, 49, 59, 48, 13, 10]
11;0

[54, 59, 49, 55, 48, 50, 51, 52, 55, 54, 57, 56, 50, 50, 54, 59, 48, 59, 48, 59, 48, 59, 48, 46, 48, 48, 59, 48, 59, 49, 59, 48, 59, 53, 53, 59, 53, 46, 49, 49, 59, 53, 46, 48, 52, 59, 57, 48, 59, 56, 50, 59, 51, 57, 59, 51, 57, 59, 57, 55, 59, 57, 55, 59, 49, 57, 53, 59, 49, 57, 53, 59, 50, 53, 55, 59, 50, 53, 53, 59, 49, 49, 59, 48, 13, 10]
6;1702347698226;0;0;0;0.00;0;1;0;55;5.11;5.04;90;82;39;39;97;97;195;195;257;255;11;0
```

Short packet (non protocol conforming):
```
[54, 59, 49, 55, 48, 50, 51, 52, 55, 54, 57, 56, 57, 53, 55, 59, 48, 59, 48, 59]
6;1702347698957;0;0;
[48, 59, 48, 46, 48, 48, 59, 48, 59, 49, 59, 48, 59, 53, 56, 59, 53, 46, 49, 49]
0;0.00;0;1;0;58;5.11
[54, 13, 10]
6

[54, 59, 49, 55, 48, 50, 51, 52, 55, 54, 57, 56, 57, 53, 55, 59, 48, 59, 48, 59, 48, 59, 48, 46, 48, 48, 59, 48, 59, 49, 59, 48, 59, 53, 56, 59, 53, 46, 49, 49, 54, 13, 10]
6;1702347698957;0;0;0;0.00;0;1;0;58;5.116
```

This later caused an array index overflow:
```
I/flutter ( 6176): MAIN | runZonedGuarded pacman | RangeError (index): Invalid value: Not in inclusive range 0..10: 22; #0      List.[] (dart:core-patch/growable_array.dart:264:36)
I/flutter ( 6176): #1      KayakFirstDescriptor.stubRecord (package:track_my_indoor_exercise/devices/device_descriptors/kayak_first_descriptor.dart:98:38)
I/flutter ( 6176): #2      DataHandler.wrappedStubRecord (package:track_my_indoor_exercise/devices/device_descriptors/data_handler.dart:88:18)
I/flutter ( 6176): #3      FitnessEquipment._mergedForYield.<anonymous closure> (package:track_my_indoor_exercise/devices/gadgets/fitness_equipment.dart:187:52)
I/flutter ( 6176): #4      MappedIterator.moveNext (dart:_internal/iterable.dart:403:20)
I/flutter ( 6176): #5      IterableNullableExtension.whereNotNull (package:collection/src/iterable_extensions.dart:605:25)
I/flutter ( 6176): #6      _SyncStarIterator.moveNext (dart:async-patch/async_patch.dart:558:14)
I/flutter ( 6176): #7      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
I/flutter ( 6176): #8      new _List._ofOther (dart:core-patch/array.dart:175:43)
I/flutter ( 6176): #9      new _List.of (dart:core-patch/array.dart:129:18)
I/flutter ( 6176): #10     new List.of (dart:core-patch/array_patch.dart:39:50)
I/flutter ( 6176): #11     Iterable.toList (dart:core/iterable.dart:497:7)
I/flutter ( 6176): #12     FitnessEquipment._mergedForYield (package:track_my_indoor_exercise/devices/gadgets/fitness_equipment.dart:189:10)
I/flutter ( 6176): #13     FitnessEquipment._listenToData (package:track_my_indoor_exercise/devices/gadgets/fitness_equipment.dart:370:24)
I/flutter ( 6176): <asynchronous suspension>
I/flutter ( 6176): #14     FitnessEquipment.pumpData.<anonymous closure> (package:track_my_indoor_exercise/devices/gadgets/fitness_equipment.dart:403:43)
I/flutter ( 6176): <asynchronous suspension>
I/flutter ( 6176): ; #0      List.[] (dart:core-patch/growable_array.dart:264:36)
I/flutter ( 6176): #1      KayakFirstDescriptor.stubRecord (package:track_my_indoor_exercise/devices/device_descriptors/kayak_first_descriptor.dart:98:38)
I/flutter ( 6176): #2      DataHandler.wrappedStubRecord (package:track_my_indoor_exercise/devices/device_descriptors/data_handler.dart:88:18)
I/flutter ( 6176): #3      FitnessEquipment._mergedForYield.<anonymous closure> (package:track_my_indoor_exercise/devices/gadgets/fitness_equipment.dart:187:52)
I/flutter ( 6176): #4      MappedIterator.moveNext (dart:_internal/iterable.dart:403:20)
I/flutter ( 6176): #5      IterableNullableExtension.whereNotNull (package:collection/src/iterable_extensions.dart:605:25)
I/flutter ( 6176): #6      _SyncStarIterator.moveNext (dart:async-patch/async_patch.dart:558:14)
I/flutter ( 6176): #7      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
I/flutter ( 6176): #8      new _List._ofOther (dart:core-patch/array.dart:175:43)
I/flutter ( 6176): #9      new _List.of (dart:core-patch/array.dart:129:18)
```

We can use `elementAtOrNull` (see https://stackoverflow.com/a/77263643/292502) to make the `KayakFirstDescriptor.stubRecord` more robust against any shortened data packets.

**Comment by MrCsabaToth** [comment]
KayakFirstDescriptor.stubRecord ended up returning null packet for shortened data #430
Otherwise the workout experiences intermittent dips

**Comment by MrCsabaToth** [comment]
The effect still comes, so I need to debug more. Akos's problem is different though, in his recording he doesn't even get to the point where the recording screen is active, his attempt fails sometimes during the connection.

**Comment by MrCsabaToth** [comment]
Re https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/issues/430#issuecomment-1851454072 when the reply to the poll command "6" was shorter: it seems that sometimes there's a rogue ['6', CR, LF] packet coming in. That early closes a packet which is in the midst of gathering. I'm adding a code to skip specific packets to handle that. Seems like after I just ignore these rogue packets the amount of short poll responses fixes.

**Comment by MrCsabaToth** [comment]
At the UTE kayak club the Canoe ergometer's console worked like a charm, for some reason the kayak ergometer's console (which supposedly should be very similar) was acting almost like Akos's video: only the workout timer was enhancing and the other metrics remained zero. The fact that the canoe console worked just fine gives me great confidence. But we still has to figure out what was going on with the kayak erg's console and Akos's console.

**Comment by MrCsabaToth** [comment]
First debug session happened on 12/19/2023, Mate was welcoming. In the upstairs gym room I successfully recorded sessions on a non sliding blue Canoe erg (2009003B).

The kayak erg console was also deep discharged, but turned on and was able to connect, but the sensors weren't registering and only the elapsed time advanced.

Downstairs there were two sliding Canoe ergs I have not debugged. There were also four C2 Row Ergs and four C2 Ski Ergs ()

**Comment by MrCsabaToth** [comment]
After the first session Akos repeated some earlier advice and also gave some new. So the basic idea is:
1. A response to a command is quasi immediate, the processing of the command may take longer. So the response just acknowledges the consuming of the command.
2. If there's no response of the receival after 1s I can repeat the command 2 more times with 1s spacing.
3. If I see a response then wait 5s to be sure that the console had time to process it.

Besides that I also noticed that in his log he issues a reset command twice, so I do that as well:
![engineer_test_seqience_pt1](https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/assets/744949/ebaf42c3-c5ba-4e53-b81c-8741d23a0803)

![engineer_test_seqience_pt2](https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/assets/744949/3c1b1671-e5c9-4386-bdbd-ef9b2cdbe278)

With these modifications I deployed a release build to my Motorola ThinkPhone to be sure I test with a release apk to rule out any difference between release and debug. The tests were successful. (Except with the kayak erg which probably has some sensor wiring, or magnet or some other issue preventing the pulse signal).

The downstairs two sliding seat canoe ergs also worked (1902075B and 1902079B).

**Comment by MrCsabaToth** [comment]
What's left is to give feedback to the user while these multiple 5s waits happen. At minimum some snack bars, but maybe even a dedicated multi-step progress bar.

**Comment by MrCsabaToth** [comment]
Unfortunately snack bars lay over the pulsating hourglass on the top. So we need something nicer. I'm thinking of a bottom drawer, we could use that for non KayakFirst cases when there's some second delay with the control point start command all that.

**Comment by MrCsabaToth** [comment]
Released with beta build 152
