### ISSUE TITLE
Crash on Android 13 with SecurityException about android.permission.BLUETOOTH_CONNECT

### ISSUE THREAD

**Issue by MrCsabaToth** [TrackMyIndoorWorkout/TrackMyIndoorWorkout#454]
```
E/AndroidRuntime( 6031): FATAL EXCEPTION: main
E/AndroidRuntime( 6031): Process: dev.csaba.track_my_indoor_exercise, PID: 6031
E/AndroidRuntime( 6031): java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@6ab3fe6a: AdapterService getRemoteName
E/AndroidRuntime( 6031): 	at com.android.bluetooth.Utils.checkPermissionForDataDelivery(Utils.java:457)
E/AndroidRuntime( 6031): 	at com.android.bluetooth.Utils.checkConnectPermissionForDataDelivery(Utils.java:489)
E/AndroidRuntime( 6031): 	at com.android.bluetooth.btservice.AdapterService$AdapterServiceBinder.getRemoteName(AdapterService.java:3019)
E/AndroidRuntime( 6031): 	at com.android.bluetooth.btservice.AdapterService$AdapterServiceBinder.getRemoteName(AdapterService.java:3010)
E/AndroidRuntime( 6031): 	at android.bluetooth.IBluetooth$Stub.onTransact(IBluetooth.java:1219)
E/AndroidRuntime( 6031): 	at android.os.Binder.execTransactInternal(Binder.java:1298)
E/AndroidRuntime( 6031): 	at android.os.Binder.execTransact(Binder.java:1252)
```

The funny thing is that android.permission.BLUETOOTH_CONNECT is specified in the AndroidManifest.xml.

**Comment by MrCsabaToth** [comment]
The interesting thing is that the Flutter Blue Plus example app has the exact same permissions as me. One difference between the manifests is that I removed the BLE feature (`<uses-feature android:name="android.hardware.bluetooth_le" android:required="true" />`) #299 because Huawei AppStore required me to remove it so the app can even start without Bluetooth being available (pretty unreasonable request BTW). Now I'm adding back that feature, but I still get the crash.

**Comment by MrCsabaToth** [comment]
Refs: https://github.com/boskokg/flutter_blue_plus/issues/434 https://github.com/boskokg/flutter_blue_plus/issues/409 https://github.com/boskokg/flutter_blue_plus/issues/370 https://github.com/boskokg/flutter_blue_plus/issues/332

**Comment by MrCsabaToth** [comment]
The crash doesn't happen if I remove `android:usesPermissionFlags="neverForLocation"` from the `<uses-permission android:name="android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation" />`. However in that case the scan doesn't return anything. So I need to experiment more.

**Comment by MrCsabaToth** [comment]
Whatever the solution will be the unreasonable Huawei requirement of no Bluetooth function (#299) will require extra attention.
I discovered that the Flutter Blue Plus example project uses `permission_handler` plugin before starting the app:

    [
      Permission.location,
      Permission.storage,
      Permission.bluetooth,
      Permission.bluetoothConnect,
      Permission.bluetoothScan
    ].request().then((status) {
      runApp(const FlutterBlueApp());
    });

I have a feeling that is the key to the solution.

**Comment by MrCsabaToth** [comment]
Not sure if related, but it's not 100% reproducable, saw it on various Android version when I was testing the fix (permission_handler calls) for this: sometimes I get
```
D/[FBP-Android](17987): [FBP-Android] onMethodCall: discoverServices
I/flutter (17987): PlatformException(discoverServices, device is disconnected, null, null)
I/flutter (17987): trace:
I/flutter (17987): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
I/flutter (17987): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
I/flutter (17987): <asynchronous suspension>
I/flutter (17987): #2      FlutterBluePlus._invokeMethod (package:flutter_blue_plus/src/flutter_blue_plus.dart:296:19)
I/flutter (17987): <asynchronous suspension>
I/flutter (17987): #3      BluetoothDevice.discoverServices (package:flutter_blue_plus/src/bluetooth_device.dart:156:7)
I/flutter (17987): <asynchronous suspension>
I/flutter (17987): #4      DeviceBase.discover (package:track_my_indoor_exercise/devices/gadgets/device_base.dart:213:18)
I/flutter (17987): <asynchronous suspension>
I/flutter (17987): #5      FitnessEquipment.discover (package:track_my_indoor_exercise/devices/gadgets/fitness_equipment.dart:673:21)
I/flutter (17987): <asynchronous suspension>
I/flutter (17987): #6      FitnessEquipment.connectOnDemand (package:track_my_indoor_exercise/devices/gadgets/fitness_equipment.dart:519:21)
I/flutter (17987): <asynchronous suspension>
I/flutter (17987): #7      FindDevicesState.goToRecording (package:track_my_indoor_exercise/ui/find_devices.dart:784:21)
I/flutter (17987): <asynchronous suspension>
I/flutter (17987): #8      FindDevicesState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:track_my_indoor_exercise/ui/find_devices.dart:984:29)
I/flutter (17987): <asynchronous suspension>
D/[FBP-Android](17987): [FBP-Android] onMethodCall: discoverServices
I/flutter (17987): PlatformException(discoverServices, device is disconnected, null, null)
I/flutter (17987): trace:
I/flutter (17987): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
I/flutter (17987): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
I/flutter (17987): <asynchronous suspension>
I/flutter (17987): #2      FlutterBluePlus._invokeMethod (package:flutter_blue_plus/src/flutter_blue_plus.dart:296:19)
I/flutter (17987): <asynchronous suspension>
I/flutter (17987): #3      BluetoothDevice.discoverServices (package:flutter_blue_plus/src/bluetooth_device.dart:156:7)
I/flutter (17987): <asynchronous suspension>
I/flutter (17987): #4      DeviceBase.discover (package:track_my_indoor_exercise/devices/gadgets/device_base.dart:222:20)
I/flutter (17987): <asynchronous suspension>
I/flutter (17987): #5      FitnessEquipment.discover (package:track_my_indoor_exercise/devices/gadgets/fitness_equipment.dart:673:21)
I/flutter (17987): <asynchronous suspension>
I/flutter (17987): #6      FitnessEquipment.connectOnDemand (package:track_my_indoor_exercise/devices/gadgets/fitness_equipment.dart:519:21)
I/flutter (17987): <asynchronous suspension>
I/flutter (17987): #7      FindDevicesState.goToRecording (package:track_my_indoor_exercise/ui/find_devices.dart:784:21)
I/flutter (17987): <asynchronous suspension>
I/flutter (17987): #8      FindDevicesState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:track_my_indoor_exercise/ui/find_devices.dart:984:29)
I/flutter (17987): <asynchronous suspension>
[GETX] OPEN DIALOG 854862702
[GETX] CLOSE DIALOG 854862702
```

**Comment by MrCsabaToth** [comment]
I wonder if https://github.com/boskokg/flutter_blue_plus/issues/501 is related to this last "device is disconnected" PlatformException

**Comment by MrCsabaToth** [comment]
Disconnect reason is now added: https://github.com/boskokg/flutter_blue_plus/issues/498

**Comment by MrCsabaToth** [comment]
So apparently others have this same SecurityException about BLUETOOTH_CONNECT, and it can be solved without permission_handler: https://github.com/boskokg/flutter_blue_plus/issues/497 https://github.com/boskokg/flutter_blue_plus/commit/5b7d1840be117f3783bc196a1a7c664477276825
