### ISSUE TITLE
FBP possibly causes Life Fitness machine support failure (when debugging the Santa Clara Marriott machines)

### ISSUE THREAD

**Issue by MrCsabaToth** [TrackMyIndoorWorkout/TrackMyIndoorWorkout#531]
The current code worked with some limitations (#462) with the McLean VA DoubleTree's machines.

In Santa Clara all types (treadmill, upright and recumbent bike, elliptical, stair climber) fail. All of them stay on the home screen and after a long wait the Bluetooth pairing (for audio or HRM) pops up.

**Comment by MrCsabaToth** [comment]
Note to self:
1. The leftmost elliptical is the `B0:1F:81:D5:91:A7` `LF1B01F81D591A7089`
2. The recumbent bike is the `B0:1F:81:D5:98:FC` `LF1B01F81D598FC090`
3. The upright bike to the left is the `B0:1F:81:D5:99:11` `LF1B01F81D59911091`

**Comment by MrCsabaToth** [comment]
The app was failing with the first character write (`lifeFitnessUserControl1MagicNumber1`) in the `LifeFitnessMixin.prePumpConfig`. When reverting back to FBP version 1.32.12 the app connects OK, so FBP screwed up soemthing.

**Comment by MrCsabaToth** [comment]
Ref https://github.com/chipweinberger/flutter_blue_plus/issues/1054

**Comment by MrCsabaToth** [comment]
Here are two logs which I made with the app's user facing logging feature. This happened on Friday night (vs the Saturday morning and afternoon debug sessions later). This contains a `secondary service not found '1826'` error.

```
2024-11-08 18:32:28.908203,ERROR,FITNESS_EQUIPMENT,_fitnessMachineFeature,getWriteSupportParameters?; PlatformException(readCharacteristic, secondary service not found '1826', null, null); #0      StandardMethodCodec.decodeEnvelope (pack
age:flutter/src/services/message_codecs.dart:648:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      FlutterBluePlus._invokeMethod (package:flutter_blue_plus/src/flutter_blue_plus.dart:614:13)
<asynchronous suspension>
#3      BluetoothCharacteristic.read (package:flutter_blue_plus/src/bluetooth_characteristic.dart:133:7)
<asynchronous suspension>
#4      FitnessEquipment._fitnessMachineFeature (package:track_my_indoor_exercise/devices/gadgets/fitness_equipment.dart:586:29)
<asynchronous suspension>
#5      FitnessEquipment.discover (package:track_my_indoor_exercise/devices/gadgets/fitness_equipment.dart:682:5)
<asynchronous suspension>
#6      FitnessEquipment.connectOnDemand (package:track_my_indoor_exercise/devices/gadgets/fitness_equipment.dart:517:21)
<asynchronous suspension>
#7      FindDevicesState.goToRecording (package:track_my_indoor_exercise/ui/find_devices.dart:781:21)
<asynchronous suspension>
#8      FindDevicesState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:track_my_indoor_exercise/ui/find_devices.dart:981:29)
<asynchronous suspension>

2024-11-08 18:32:28.912365,INFO,FITNESS_EQUIPMENT,_checkManufacturerName,ensuring that manufacturer name (null) contains manufacturer name part LF
2024-11-08 18:32:29.416731,ERROR,FITNESS_EQUIPMENT,_fitnessMachineFeature,getWriteSupportParameters?; PlatformException(readCharacteristic, secondary service not found '1826', null, null); #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      FlutterBluePlus._invokeMethod (package:flutter_blue_plus/src/flutter_blue_plus.dart:614:13)
<asynchronous suspension>
#3      BluetoothCharacteristic.read (package:flutter_blue_plus/src/bluetooth_characteristic.dart:133:7)
<asynchronous suspension>
#4      FitnessEquipment._fitnessMachineFeature (package:track_my_indoor_exercise/devices/gadgets/fitness_equipment.dart:586:29)
<asynchronous suspension>
#5      FitnessEquipment.discover (package:track_my_indoor_exercise/devices/gadgets/fitness_equipment.dart:682:5)
<asynchronous suspension>
#6      FitnessEquipment.connectOnDemand (package:track_my_indoor_exercise/devices/gadgets/fitness_equipment.dart:517:21)
<asynchronous suspension>
#7      RecordingState._connectOnDemand (package:track_my_indoor_exercise/ui/recording.dart:293:20)
<asynchronous suspension>

2024-11-08 18:32:29.420516,INFO,FITNESS_EQUIPMENT,_checkManufacturerName,ensuring that manufacturer name (null) contains manufacturer name part LF
2024-11-08 18:32:29.562730,INFO,FITNESS_EQUIPMENT,refreshFactors,_powerFactor 1.0, _calorieFactor 1.0, _hrCalorieFactor 1.0, _hrmCalorieFactor 1.0
2024-11-08 18:32:29.584156,ERROR,MAIN,runZonedGuarded,pacman; PlatformException(setNotifyValue, secondary service not found 'fb694b90-f49e-4597-8306-171bba78f846', null, null); #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      FlutterBluePlus._invokeMethod (package:flutter_blue_plus/src/flutter_blue_plus.dart:614:13)
<asynchronous suspension>
#3      BluetoothCharacteristic.setNotifyValue (package:flutter_blue_plus/src/bluetooth_characteristic.dart:275:22)
<asynchronous suspension>
#4      LifeFitnessMixin.prePumpConfig (package:track_my_indoor_exercise/devices/gadgets/life_fitness_mixin.dart:31:5)
<asynchronous suspension>
#5      LifeFitnessEllipticalDescriptor.prePumpConfiguration (package:track_my_indoor_exercise/devices/device_descriptors/life_fitness_elliptical_descriptor.dart:27:5)
<asynchronous suspension>
#6      FitnessEquipment.prePumpConfiguration (package:track_my_indoor_exercise/devices/gadgets/fitness_equipment.dart:526:5)
<asynchronous suspension>
#7      RecordingState._connectOnDemand (package:track_my_indoor_exercise/ui/recording.dart:297:9)
<asynchronous suspension>
```

[DebugLogs_20241109T023844361206Z.csv](https://github.com/user-attachments/files/17693645/DebugLogs_20241109T023844361206Z.csv)

[DebugLogs_20241109T024511184453Z.csv](https://github.com/user-attachments/files/17693646/DebugLogs_20241109T024511184453Z.csv)

But than I'm confused if the FBP at the time of that log was 1.34.1 or the latest 1.34.4. So I dampened the title of the error, and will need to repeat debugging again when I'll be at a Marriott, DoubleTree or Hilton with Life Fitness

**Comment by MrCsabaToth** [comment]
My latest tests at Hyatt Centric Mountain View was quite great. I didn't have to quit the app to start activities on bike, then on an elliptical, and finally on a treadmill. There wasn't a stair climber machine though.

There was a set of new console on two upright bikes I was not able to get working because supposedly they were low on battery? But that's a separate issue.
@cagnulein have you seen these? I don't think they are FTMS compatible, the video looks like 7 years old:
* https://www.youtube.com/watch?v=5URV2uN3H4s
* https://www.schellers.com/product/life-fitness-myride-vx-console-10447.htm

![Image](https://github.com/user-attachments/assets/efea95e0-46e6-4081-8d5e-45ef57bb46cf)

![Image](https://github.com/user-attachments/assets/44e7fcf3-57f4-45d8-bf36-536052da4e54)

![Image](https://github.com/user-attachments/assets/eadb7577-65d3-41ad-9c85-bf676786330b)
